Add zip size check

diff --git a/board/fischertechnik/TXT/rootfs/sbin/system-update b/board/fischertechnik/TXT/rootfs/sbin/system-update
--- a/board/fischertechnik/TXT/rootfs/sbin/system-update
+++ b/board/fischertechnik/TXT/rootfs/sbin/system-update
@@ -1,6 +1,7 @@
 #!/bin/sh
 export PATH=/bin/:/usr/bin:/sbin:/usr/sbin
 BASE_URL="https://github.com/ftCommunity/ftcommunity-TXT/releases/download"
+TAG_RELEASE_API_URL="https://api.github.com/repos/ftCommunity/ftcommunity-TXT/releases/tags"
 TARGET_VERSION="$1"
 CURRENT_VERSION="$(cat /etc/fw-ver.txt | cut -f1 -d"-")"
 ARCHIVE="ftcommunity-txt-${TARGET_VERSION}.zip"
@@ -47,8 +48,16 @@ if [ $? != 0 ] ; then
 fi
 
 echo "validating update..."
+SIZE=$(wget -qO- "${TAG_RELEASE_API_URL}/v${TARGET_VERSION}" | get_size_json.py)
+SIZE_EXEC_OK=$?
 # TODO: real check of update files against a known developer signature
-if ! [ -f "${TEMPDIR}/${ARCHIVE}" ] ; then
+# Currently we just check the file size
+if ! [ -f "${TEMPDIR}/${ARCHIVE}" ] || [ $SIZE_EXEC_OK != 0 ]; then
+  echo "validate update failed" >&2
+  exit 20
+fi
+
+if ! [ $(wc -c < "${TEMPDIR}/${ARCHIVE}") = $SIZE ]; then
   echo "validate update failed" >&2
   exit 20
 fi
