Initialize SD card on first boot

diff --git a/board/fischertechnik/TXT/initramfs/init b/board/fischertechnik/TXT/initramfs/init
--- a/board/fischertechnik/TXT/initramfs/init
+++ b/board/fischertechnik/TXT/initramfs/init
@@ -16,6 +16,12 @@ mount -t devtmpfs devtmpfs /dev
 mkdir -p /dev/pts
 mkdir -p /dev/shm
 
+if ! [ -b /dev/mmcblk0p2 ] ; then
+  if ! /repartition-sd-card ; then
+     echo "failed to repartition the SD card. Dropping to a shell"
+     exec /bin/sh
+  fi
+fi
 
 # mount SD card partitions.
 mount -t vfat /dev/mmcblk0p1 /media/sdcard/boot -o dmask=022,fmask=133,flush
